# Generated by Django 4.2 on 2025-04-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.usercourse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='advanced_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='beginner_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='intermediate_progress',
            field=models.IntegerField(default=0),
        ),
    ]
