# Generated by Django 4.2 on 2025-04-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprogress_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='course',
            new_name='user_course',
        ),
    ]
